### PR TITLE
Fix digest, add target, path and tag_with_latest options

### LINKED ISSUE #7: Build context
My repo contains multiple image files. I specify the `Dockerfile` with:

```
build_file: conda/Dockerfile
```

but the context is still set to the root of the repo.

Could you add an option to set the context dir?

### PR DESCRIPTION
**Pull request by somdoron**
fixes #7

### CODE REVIEW

File: entrypoint.sh [hunk 1]
```diff
@@ -69,7 +86,13 @@ EOF
 
 if [ ! -z $INPUT_SKIP_UNCHANGED_DIGEST ]; then
     export DIGEST=$(cat digest)
-    export REMOTE=$(reg digest "$IMAGE" | tail -1)
+
+    if [ "$REGISTRY" == "docker.pkg.github.com" ]; then
```
Comment (aexvir) [inline entrypoint.sh:90]: Huh, nice catch! Didn't really think about this, and it seems I didn't test it either 😅
